DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS ckpt;
DROP TABLE IF EXISTS model;
DROP TABLE IF EXISTS dataset;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userName TEXT UNIQUE NOT NULL,
  preferences JSON
);

CREATE TABLE ckpt (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ckptName TEXT NOT NULL,
  userId INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  class TEXT NOT NULL,
  stats JSON,
  epochs INTEGER NOT NULL DEFAULT 30,
  ensembleSize INTEGER NOT NULL,
  trainingSize INTEGER NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT 0,
  FOREIGN KEY (userId) REFERENCES user (id),
  CONSTRAINT uqCkptNames UNIQUE(ckptName, userId)
);

CREATE TABLE model (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ckptId INTEGER NOT NULL,
  FOREIGN KEY (ckptId) REFERENCES ckpt (id)
);

CREATE TABLE dataset (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datasetName TEXT NOT NULL,
  userId INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  class TEXT NOT NULL,
  FOREIGN KEY (userId) REFERENCES user (id),
  CONSTRAINT uqDatasetNames UNIQUE(datasetName, userId)
);

INSERT INTO user (userName) VALUES ("DEFAULT")